
export interface Issue {
  id: number;
  title: string;
  description: string;
  component?: string;
  severity?: 'critical' | 'high' | 'medium' | 'low';
  resolution?: string;
  tags?: string[];
  category?: string;
}

export type SeverityType = 'critical' | 'high' | 'medium' | 'low' | 'all';
export type ComponentFilter = string | 'all';
export type CategoryFilter = string | 'all';

// Standard Kubernetes component types for reference
export const standardKubernetesComponents = [
  'API Server',
  'etcd',
  'Scheduler',
  'Controller Manager',
  'kubelet',
  'kube-proxy',
  'Container Runtime',
  'CoreDNS',
  'Networking',
  'Storage',
  'Authentication',
  'RBAC',
  'ConfigMap',
  'Secret',
  'Pod',
  'Deployment',
  'StatefulSet',
  'DaemonSet',
  'Job',
  'CronJob',
  'Service',
  'Ingress',
  'PersistentVolume',
  'PersistentVolumeClaim',
  'Namespace',
  'ResourceQuota',
  'LimitRange',
  'HorizontalPodAutoscaler',
  'VerticalPodAutoscaler',
  'NetworkPolicy',
  'PodSecurityPolicy',
  'ServiceAccount',
  'CustomResourceDefinition',
  'Operator',
  'Helm',
  'kubectl',
  'Monitoring',
  'Logging',
  'Dashboard',
  'Admission Controller',
  'Security',
  'RBAC',
  'CSI',
  'CNI',
  'CRI',
  'Cluster Autoscaler',
  'External DNS',
  'Certificate Manager',
  'Kube State Metrics',
  'Node Problem Detector',
  'Prometheus',
  'Grafana',
  'Fluentd',
  'Elasticsearch',
  'Kibana',
  'Istio',
  'Linkerd',
  'Helm Chart',
  'Kustomize',
  'Velero',
  'Argo CD',
  'Flux CD',
  'Tekton',
  'Jenkins X',
  'Kube-bench',
  'Kube-hunter',
  'Falco',
  'OPA Gatekeeper',
  'Rook',
  'Cilium',
  'Calico',
  'Flannel',
  'Weave Net',
  'Multus',
  'MetalLB',
  'ExternalDNS',
  'cert-manager',
  'OAuth2 Proxy',
  'Kong',
  'Traefik',
  'Nginx',
  'HAProxy',
  'Envoy',
  'ConfigMap',
  'Secret',
  'Volume',
  'Node',
  'Kubeadm',
  'Cloud Controller Manager',
  'Cluster API',
  'Taints and Tolerations',
  'NodeAffinity',
  'PodAffinity',
  'PodAntiAffinity',
  'Init Containers',
  'Sidecar Containers',
  'Headless Service',
  'ExternalName Service',
  'LoadBalancer Service',
  'NodePort Service',
  'ClusterIP Service',
  'EndpointSlice',
  'Endpoint',
  'Metrics Server',
  'Kube Scheduler',
  'CRI-O',
  'containerd',
  'Docker',
  'runc',
  'Security Context',
  'PodSecurityContext',
  'NetworkPolicy',
  'RuntimeClass',
  'PriorityClass',
  'HPA',
  'VPA',
  'Probes',
  'Readiness Probe',
  'Liveness Probe',
  'Startup Probe',
  'Resource Limits',
  'Resource Requests',
  'Quality of Service',
  'Disruption Budget'
];
